<?php

/**
 * @file
 * Contains explore.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function explore_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the explore module.
    case 'help.page.explore':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is for exploration perspective.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function explore_theme() {
  return [
    'explore' => [
      'template' => 'explore',
      'render element' => 'children',
    ],
  ];
}
